django_pass/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

#template urls
app_name='basic_app'

urlpatterns=[

    url('register/',views.register,name='register'),
    url('login/',views.user_login,name='userlogin'),

]

django_pass/django_pass/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('basicapp/',include('basic_app.urls')),
    path('logout/',views.user_logout,name='logout'),



]

django_pass/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    on_delete=models.DO_NOTHING

    user= models.OneToOneField(User,on_delete)

    #addtional
    portfolio_site=models.URLField(blank=True)
    profile_pic=models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username
         #username is default attribute of User package

django_pass/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model=User
        fields=('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
     class Meta:
         model=UserProfileInfo
         fields=('portfolio_site','profile_pic')

django_pass/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm,UserProfileInfoForm

# for login, these are the packages
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
# Create your views here.
def index(request):
    return render(request,'basic_app/index.html')

def register(request):

    registered=False

    if request.method=='POST':
        user_form=UserForm(data=request.POST)
        profile_form=UserProfileInfoForm(data=request.POST)


        if user_form.is_valid() and profile_form.is_valid():

            user=user_form.save()
            user.set_password(user.password) # hashing the password here
            user.save()

            profile=profile_form.save(commit=False)
            profile.user=user #one to one relatiosnhip

            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']
            profile.save()

            registered=True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form=UserForm()
        profile_form=UserProfileInfoForm()

    return render(request,'basic_app/registration.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})





def user_login(request):

    if request.method=='POST':

        username = request.POST.get('username') #'username' here is the name of the input box
        password=request.POST.get('password')

        user=authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse('Account is not active')

        else:
            print('Someone logged in and failed')
            print('UserName: {} and Password: {}'.format(username,password))
            return HttpResponse('Invalid Credentials!')
    else:
        return render(request,'basic_app/login.html')


@login_required # this decorator to show only when a user is loggen in not to every one
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

django_pass/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title></title>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="navbar navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:register' %}">Register</a></li>

          {% if user.is_authenticated %}
          <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
          {% else %}
          <li><a class="navbar-link" href="{% url 'basic_app:userlogin' %}">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

django_pass/templates/basic_app/index.html
{% extends 'basic_app/base.html' %}
{% block body_block %}

<div class="jumbotron">
  <h1>django here</h1>
</div>
{% endblock %}

django_pass/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}

<div class="jumbotron">
  <h1>Please Login!</h1>
  <form action={% url 'basic_app:userlogin' %} method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter your username here">
    <label for="password">Password:</label>
    <input type="password" name="password">
    <input type="submit"  value="Login">
  </form>
</div>


{% endblock %}

django_pass/templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}


{% block body_block %}
<div class="jumbotron">
  {% if registered %}
  <h1>Thank you for registering!</h1>
  {% else %}
  <h1>fill out the form here</h1>

  <form method="post" enctype="multipart/form-data"> <!- here enctype is for image uploading->
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" value="Register">
  </form>

  {% endif %}
</div>

{% endblock %}